name: DiscordVerify
authors: [bobcatsss,brainsynder]
depends: [SimpleAPI]
version: 0.1
main: me.bobcatsss.discordverify.Core
commands:
   verify:
      description: Gives you a code to register on Discord.